### ISSUE TITLE
CTimeseriesTests are failing

### ISSUE THREAD

**Issue by KrennKristof** [wuttem/cattledb#6]
current version on master does not succeed on test execution of CTimeSeriesTests, executed in docker

PIP: pip 20.2.4 from /usr/local/lib/python3.6/site-packages/pip (python 3.6)
cattledb: 0.6.2

FAILED tests/test_ctimeseries.py::CTimeSeriesTest::test_base - TypeError: 'NoneType' object is not callable
FAILED tests/test_ctimeseries.py::CTimeSeriesTest::test_canada - TypeError: 'NoneType' object is not callable
FAILED tests/test_ctimeseries.py::CTimeSeriesTest::test_index - TypeError: 'NoneType' object is not callable
FAILED tests/test_ctimeseries.py::CTimeSeriesTest::test_timezone - TypeError: 'NoneType' object is not callable
FAILED tests/test_ctimeseries.py::CTimeSeriesTest::test_trim - TypeError: 'NoneType' object is not callable
FAILED tests/test_ctimeseries.py::CTimeSeriesTest::test_trim_exact - TypeError: 'NoneType' object is not callable
FAILED tests/test_ctimeseries.py::CTimeSeriesTest::test_vienna - TypeError: 'NoneType' object is not callable

self = <tests.test_ctimeseries.CTimeSeriesTest testMethod=test_vienna>

    def test_vienna(self):
>       t1 = FastFloatTSList("abc", "def")

tests/test_ctimeseries.py:61: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <cattledb.core._timeseries.FastFloatTSList object at 0x7f56681e8470>, key = 'abc', metric = 'def'

    def __init__(self, key, metric):
>       self._data = self.__container__(key, metric)
E       TypeError: 'NoneType' object is not callable

cattledb/core/_timeseries.py:175: TypeError

**Comment by wuttem** [comment]
It seems like the C-Extension is not build. Try the following (maybe in a clean environment):
```python
pip install -r requirements.txt
pip install pytest mock
python setup.py install
```
Is there any output from cmake or GCC that indicates any errors when building?
If everything is build run:
````
pytest tests/test_ctimeseries.py
```
Does it still not work ?
